### ISSUE TITLE
Set selected segment programmatically

### ISSUE THREAD

**Issue by riccardoch** [attheodo/ATHMultiSelectionSegmentedControl#6]
I'd like to show selected segments programmatically, but I did't find the method.
I've tried with:
```
let selectedSegments = [0, 2, 4]
self.multiSelectionSegmentControl.selectedSegmentIndices = selectedSegments
```
but it didn't work

**Comment by RosscoMT** [comment]
You need to have the view initialised and drawn before you can select the segments. I.e Setup the view in the viewDidLoad() then in ViewWillAppear() set the selectedSegments.

**Comment by M-HERBRICH-ITC** [comment]
For me it's also not working, even if I call layoutSubviews after setting selectedSegmentIndices :(

**Comment by attheodo** [comment]
Can you try the `setEnabled(Bool, forSegmentAtIndex: Int)` method until I support setting it via `selectedSegmentIndices`?

**Comment by thomasmbr** [comment]
Has anyone been able to do select items programmatically ?? I'm trying to do this too, but to no avail yet.

**Comment by M-HERBRICH-ITC** [comment]
@thomasmbr 
For me it's working with this code:
```
        self.segmentControl.insertSegmentsWithTitles(segments)
        DispatchQueue.main.async {
            self.segmentControl.selectedSegmentIndices = self.selectedIndices //it's an array of Integers
        }
```

**Comment by thomasmbr** [comment]
Great, worked out for me @M-HERBRICH-ITC . Thank you very much.
